project:
  type: book
  output-dir: docs

book:
  title: "TPI"
  search: true
  repo-url: https://github.com/ciupava/TPI/tree/master/docs
  downloads: [pdf]
  chapters:
    - index.qmd
    - intro.qmd
    - jobacc.qmd
    - part: "Running TPI"
      chapters:
        - data.qmd
        - data_prep.qmd
        - workflow.qmd
   
format:
  html:
    theme: cosmo
  pdf: default
