project:
  type: book

book:
  title: "TPI - Target Population Index"
  search: true
  repo-url: https://github.com/ciupava/TPI/tree/master/docs
  downloads: [pdf]
  chapters:
    - index.qmd
   
format:
  html:
    theme: cosmo
  pdf: default
